### PR TITLE
feat : add docker

### LINKED ISSUE #2: Add Docker support
Add built in docker suppert with docker-compose file.

### PR DESCRIPTION
**Pull request by mhrnnoi**
added docker compose , docker ignore and docker file
and remove swagger  if condition to able to use in any enivironment

### CODE REVIEW

**Comment by mehmet-karagoz** [comment]
How to run it using Docker, because when you open Visual Studio, I can't see docker compose to build it.

**Review by mehmet-karagoz — COMMENTED** [review]
How to run it using Docker, because when you open Visual Studio, I can't see docker compose to build it.

**Comment by mhrnnoi** [comment]
In order to run the project using Docker, there are a few steps that need to be taken. First, you'll need to install Docker on your machine if you haven't already. Once you've done that, you can use the Docker Compose file I provided to build and run the containers.
the docker compose file is located in rood directory :  Car-Rent-Design-Pattern-Course 

Here are the steps to get started:

Clone the repository to your local machine.
Install Docker if you haven't already.
Navigate to the root directory of the repository.
type  docker-compose up in terminal to build and run the containers.
Access the application at http://localhost:8080.
Please let me know if you have any questions or if there's anything else I can do to help. Thank you for your time and consideration.

**Review by mehmet-karagoz — APPROVED** [review]
It would be better if it was run as built in via Visual Studio, but it is OK.

**Comment by mhrnnoi** [comment]
> It would be better if it was run as built in via Visual Studio, but it is OK.
Thank you for approving my pull request. I understand that running the docker container via Visual Studio's built-in tools might be preferable, but since I use Visual Studio Code and prefer to write the docker file manually, I thought it would be a good addition to include the docker file and compose file in the repository.
Thanks again for the opportunity to contribute!"

**Pull request merged**
